// Gifs animados de hasaneyldrm/exercises-dataset. Media (c) Gym visual
// (https://gymvisual.com/), redistribuida en ese repo con permiso propio de ellos
// -- NO con licencia MIT del resto del repo. Uso aqui autorizado explicitamente por
// Tobias asumiendo el riesgo de contenido de terceros (ver NOTICE.md del dataset).
// Condicion obligatoria de esa licencia: toda pantalla que muestre esta media tiene
// que mostrar la atribucion "(c) Gym visual -- https://gymvisual.com/" (ver
// components/routines/MediaAttribution.js). No subir de la resolucion 180x180 original.
//
// Matcheo hecho a mano contra data/exercises.json del dataset (1324 ejercicios) -- el
// scoring automatico por nombre+equipo se uso solo para generar candidatos, cada uno
// se verifico leyendo las instructions en ingles antes de aceptarlo. Se dejo en null
// cuando no habia una animacion real del mismo movimiento (ej. face pull, dead hang,
// band pull-apart no existen en este dataset) en vez de forzar un match aproximado.
export const MEDIA_MAP = {
  "Press de banca con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0025-EIeI8Vf.gif",
  "Press inclinado con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0047-3TZduzM.gif",
  "Press de banca con mancuernas": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0289-SpYC0Kp.gif",
  "Press inclinado con mancuernas": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0314-ns0SIbU.gif",
  "Aperturas con mancuernas": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0308-yz9nUhF.gif",
  "Cruce de poleas": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1269-UKWTJWR.gif",
  "Press de pecho en máquina": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0577-T0yTjgW.gif",
  "Flexiones de brazos": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0662-I4hDWkc.gif",
  "Fondos en paralelas": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0251-9WTm7dq.gif",
  "Remo con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0027-eZyBC3j.gif",
  "Remo con mancuerna a una mano": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1330-ZIViNh1.gif",
  "Jalón al pecho en polea": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0198-RVwzP10.gif",
  "Remo sentado en polea": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0861-fUBheHs.gif",
  "Remo en máquina": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1350-7I6LNUG.gif",
  "Dominadas": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0652-lBDjFxJ.gif",
  "Encogimientos con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0095-dG7tG5y.gif",
  "Encogimientos con mancuernas": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0406-NJzBsGJ.gif",
  "Face pull en polea": null,
  "Encogimientos en máquina": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0604-ZZKbeMw.gif",
  "Remo invertido": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0499-bZGHsAZ.gif",
  "Press militar con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1456-wdRZISl.gif",
  "Press de hombros con mancuernas": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0405-znQUdHY.gif",
  "Press de hombros en máquina": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0603-67n3r98.gif",
  "Flexiones pike": null,
  "Elevaciones laterales con mancuerna": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0334-DsgkuIt.gif",
  "Elevaciones laterales en polea": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0178-goJ6ezq.gif",
  "Elevaciones laterales en máquina": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0584-dRTfGZT.gif",
  "Aperturas posteriores con mancuerna": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0378-8DiFDVA.gif",
  "Aperturas posteriores en polea": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0225-P5p0j8B.gif",
  "Contractora inversa": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0602-myfUsKf.gif",
  "Elevación Y en prono": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/3541-PbzNu7c.gif",
  "Curl con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0031-25GPyDY.gif",
  "Curl con mancuerna": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0294-NbVPDMW.gif",
  "Curl martillo con mancuerna": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0313-slDvUAU.gif",
  "Curl en polea": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0868-G08RZcQ.gif",
  "Curl en máquina": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0575-q6y3OhV.gif",
  "Curl predicador": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0070-qOgPVf6.gif",
  "Dominadas supinas": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1326-T2mxWqc.gif",
  "Press francés con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0061-iZop9xO.gif",
  "Press cerrado con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0030-J6Dx1Mu.gif",
  "Extensión de tríceps con mancuerna": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/2188-kont8Ut.gif",
  "Extensión de tríceps en polea": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0201-3ZflifB.gif",
  "Extensión de tríceps en máquina": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0607-Ser9eQp.gif",
  "Fondos en banco": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1399-9RT8oQW.gif",
  "Curl de muñeca con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0126-82LxxkW.gif",
  "Curl de muñeca en polea": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0247-LrV4s90.gif",
  "Curl de muñeca con mancuerna": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0364-q8aHNoF.gif",
  "Curl de muñeca inverso con mancuerna": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0385-BLCvwr2.gif",
  "Dead hang": null,
  "Sentadilla con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0043-qXTaZnJ.gif",
  "Zancadas con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0054-t8iSghb.gif",
  "Sentadilla goblet con mancuerna": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1760-yn8yg1r.gif",
  "Zancadas con mancuernas": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0336-RRWFUcw.gif",
  "Prensa de piernas": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0739-10Z2DXU.gif",
  "Extensión de cuádriceps en máquina": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0585-my33uHU.gif",
  "Sentadilla con peso corporal": null,
  "Zancadas con peso corporal": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1460-IZVHb27.gif",
  "Peso muerto rumano con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0085-wQ2c4XD.gif",
  "Peso muerto rumano con mancuernas": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1459-rR0LJzx.gif",
  "Curl femoral en máquina": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0586-17lJ1kr.gif",
  "Peso muerto rumano a una pierna": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1757-gKozT8X.gif",
  "Hip thrust con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0058-SNFfUff.gif",
  "Hip thrust con mancuerna": null,
  "Zancada búlgara con mancuernas": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0410-qx4fgX7.gif",
  "Patada de glúteo en máquina": null,
  "Puente de glúteo": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/3013-u0cNiij.gif",
  "Aductores en máquina": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0598-oHsrypV.gif",
  "Aducción de cadera en polea": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0168-hBGWILP.gif",
  "Sentadilla sumo con mancuerna": null,
  "Aducción de cadera tumbado": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/3667-c8f5cSY.gif",
  "Elevación de talones con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1372-8ozhUIZ.gif",
  "Elevación de talones con mancuernas": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0417-dPmaUaU.gif",
  "Elevación de talones en máquina": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0605-ykUOVze.gif",
  "Elevación de talones con peso corporal": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1373-bJYHBIN.gif",
  "Crunch abdominal": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0274-TFqbd8t.gif",
  "Plancha abdominal": null,
  "Elevación de piernas colgado": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0472-I3tsCnC.gif",
  "Crunch en polea": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0175-WW95auq.gif",
  "Crunch en máquina": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/1452-Wgaz7pm.gif",
  "Giro ruso con mancuerna": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0846-fZFZ704.gif",
  "Peso muerto con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0032-ila4NZS.gif",
  "Buenos días con barra": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0044-XlZ4lAC.gif",
  "Buenos días con mancuerna": null,
  "Extensión lumbar en máquina": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0573-rUXfn3R.gif",
  "Hiperextensión con peso corporal": null,
  "Swing con kettlebell": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0549-UHJlbu3.gif",
  "Sentadilla goblet con kettlebell": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0534-ZA8b5hc.gif",
  "Peso muerto rumano con kettlebell": null,
  "Apertura con banda": null,
  "Elevación lateral con banda": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0977-sTg7iys.gif",
  "Curl con banda": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0968-3omWx6P.gif",
  "Extensión de tríceps con banda": "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/videos/0998-obe5LMq.gif",
};
